global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'api-gateway'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'api-gateway:8070' ]

- job_name: 'student-services'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'student-services:8074' ]

- job_name: 'teacher-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'teacher-service:8075' ]

- job_name: 'homework-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'homework-service:8076' ]

# Jika menggunakan Node Exporter untuk host metrics
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
